name: WePY Templates Build And Upload to Tencent COS

on: 
  push:
    branches:
      - 2.0.x
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - name: If there are build changes, then push them
      run: |
        [ $(git status -s | wc -l) -gt 0 ] &&  git commit -am 'build: Github Actions Build' && git push
    - run: npm run cos
      env:
        CI: true
        COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}

